name: Deploy to FTP Server

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          ftp-server: ftp://ftpupload.net
          ftp-username: if0_36582224
          ftp-password: ZRKXUectQ40IqO
          local-dir: ./
          git-ftp-args: --auto-init

